name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y gettext libappstream-dev libflatpak-dev libgee-0.8-dev libgranite-dev libgtk-3-dev libhandy-0.0-dev libjson-glib-dev libpackagekit-glib2-dev libsoup2.4-dev libxml2-dev libxml2-utils libpolkit-gobject-1-dev meson valac
    - name: Build
      run: |
        meson build --prefix=/usr -Dinstalled_tests=true
        ninja -C build
        ninja -C build install
    - name: Test
      run: |
        apt install -y flatpak gnome-desktop-testing python3-behave python3-pip python3-cairo python3-pyatspi at-spi2-core libatspi2.0-dev dbus-x11 xvfb appstream-data-pantheon
        pip3 install dogtail
        xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" dbus-run-session -- /usr/libexec/io.elementary.appcenter/installed-tests/test-runner.sh "gnome-desktop-testing-runner io.elementary.appcenter"

  lint:

    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
